
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Sat Apr 02 03:58:31 CST 2016
//----------------------------------------------------

package logic.interpreter;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int HAZ = 11;
  public static final int SB_LAPIZ = 13;
  public static final int PON_RUMBO = 9;
  public static final int AV = 3;
  public static final int PARA = 12;
  public static final int RE = 4;
  public static final int CENTRO = 10;
  public static final int PC_IZQ = 15;
  public static final int PC_DER = 16;
  public static final int BJ_LAPIZ = 14;
  public static final int PON_POS = 8;
  public static final int FLOAT = 22;
  public static final int FUNC = 20;
  public static final int EOF = 0;
  public static final int GI = 6;
  public static final int error = 1;
  public static final int GD = 5;
  public static final int ENTERO = 21;
  public static final int PARAM = 19;
  public static final int ESPACIO = 17;
  public static final int REPITE = 7;
  public static final int FIN = 2;
  public static final int VAR = 18;
}

