
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Wed Mar 23 01:53:01 CST 2016
//----------------------------------------------------

package logic;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int HAZ = 12;
  public static final int SB_LAPIZ = 14;
  public static final int PON_RUMBO = 10;
  public static final int AV = 4;
  public static final int PARA = 13;
  public static final int RE = 5;
  public static final int CENTRO = 11;
  public static final int PC_IZQ = 16;
  public static final int PC_DER = 17;
  public static final int BJ_LAPIZ = 15;
  public static final int PON_POS = 9;
  public static final int FUNC = 21;
  public static final int EOF = 0;
  public static final int GI = 7;
  public static final int error = 1;
  public static final int GD = 6;
  public static final int PROC = 2;
  public static final int ENTERO = 22;
  public static final int PARAM = 20;
  public static final int ESPACIO = 18;
  public static final int REPITE = 8;
  public static final int FIN = 3;
  public static final int VAR = 19;
}

